version: '3.9'

services:

  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    hostname: haproxy
    domainname: haproxy
    user: "root"
    ports:
      - "443:443"
      - "80:80"
      - "70:70"      
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
      - ./certs:/etc/ssl
    networks:
        - haproxy-tier
      
  whoami1:
    image: containous/whoami
    container_name: whoami1
    hostname: whoami1
    domainname: whoami1
#    ports:
#      - 8081:80 
    networks:
      - haproxy-tier      

  whoami2:
    image: containous/whoami
    container_name: whoami2
    hostname: whoami2
    domainname: whoami2
#    ports:
#      - 8082:80 
    networks:
      - haproxy-tier 
     
     
networks:
  haproxy-tier:
    driver: bridge     